branch-defaults:
  default:
    environment: Karim-env
environment-defaults:
  Karim-env:
    branch: null
    repository: null
global:
  application_name: karim
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
